custom_dict = {
    # V2 has no runtime ToneSandhi; freeze common lexical neutral tone here.
    '妈妈': [['ma1'], ['ma5']],
    '不得了':[['bu4'],['de2'],['liao3']],
    '了如指掌':[['liao3'],['ru2'],['zhi3'],['zhang3']],
    '了却':[['liao3'],['que4']],
    '重重地':[['zhong4'],['zhong4'],['de']],
    '重重叹': [['zhong4'], ['zhong4'], ['tan4']],
    '周长': [['zhou1'], ['chang2']],
    '圆周长': [['yuan2'], ['zhou1'], ['chang2']],
    '岑夫子':[['ceng2'], ['fu1'], ['zi3']],
    '困难重重': [['kun4'], ['nan2'], ['chong2'], ['chong2']],
    '重重障碍': [['chong2'], ['chong2'], ['zhang4'], ['ai4']],
    '重重困难': [['chong2'], ['chong2'], ['kun4'], ['nan2']],
    '谍影重重':[['die2'],['ying3'],['chong2'],['chong2']],
    '这得':[['zhe4'],['dei3']],
    '得加钱':[['dei3'],['jia1'],['qian2']],
    '那得':[['na4'],['dei3']],
    '得亏':[['dei3'],['kui1']],
    '要害':[['yao4'],['hai4']],
    '要塞':[['yao4'],['sai4']],
    '要求':[['yao1'],['qiu2']],
    '要挟':[['yao1'],['xie2']],
    '着实':[['zhuo2'],['shi2']],
    '穿着':[['chuan1'],['zhuo2']],
    '衣着':[['yi1'],['zhuo2']],
    '弹起':[['tan2'],['qi3']],
    '弹跳':[['tan2'],['tiao4']],
    '大夫':[['dai4'],['fu']],
    '尉迟':[['yu4'],['chi2']],
    '哪吒':[['ne2'],['zha']],
    '夫差':[['fu1'],['chai1']],
    '刘禅':[['liu2'],['shan4']],
    '查良镛':[['zha1'],['liang2'],['yong1']],
    '曾志伟':[['zeng1'],['zhi4'],['wei3']],
    '可汗':[['ke4'],['han2']],
    '单雄信':[['shan4'],['xiong2'],['xin4']],
    '华山':[['hua4'],['shan1']],
    '华为':[['hua2'],['wei2']],
    # Proper noun; pypinyin's default lexical reading is zhong4-qing4.
    '重庆':[['chong2'],['qing4']],
    # In this construction 都 means “all/everything”, not the noun 都会.
    '什么都会':[['shen2'],['me5'],['dou1'],['hui4']],
    '东莞':[['dong1'],['guan3']],
    '济南':[['ji3'],['nan2']],
    '东阿':[['dong1'],['e1']],
    '蚌埠':[['beng4'],['bu4']],
    '朝歌':[['zhao1'],['ge1']],
    '六安':[['lu4'],['an1']],
    '台州':[['tai1'],['zhou1']],
    '丽水':[['li2'],['shui3']],
    '阿房宫':[['e1'],['pang2'],['gong1']],
    '吐蕃':[['tu3'],['bo1']],
    # Tibetan script/language: 藏文 is read zàng-wén, not cáng-wén.
    '藏文':[['zang4'],['wen2']],
    '藏塔':[['zang4'],['ta3']],
    '秘鲁':[['bi4'],['lu3']],
    '柏林':[['bo2'],['lin2']],
    '将进酒':[['qiang1'],['jin4'],['jiu3']],
    '君子好逑':[['jun1'],['zi3'],['hao3'],['qiu2']],
    '吾日三省吾身':[['wu2'],['ri4'],['san1'],['xing3'],['wu2'],['shen1']],
    '不亦说乎':[['bu2'],['yi4'],['yue4'],['hu1']],
    '春风拂槛露华浓':[['chun1'],['feng1'],['fu2'],['jian4'],['lu4'],['hua2'],['nong2']],
    '天姥吟':[['tian1'],['mu3'],['yin2']],
    '清平乐':[['qing1'],['ping2'],['yue4']],
    '重重的': [['zhong4'], ['zhong4'], ['de']],
    '重算': [['chong2'], ['suan4']],
    '便宜': [['pian2'], ['yi']],
    '单老师': [['shan4'], ['lao3'], ['shi1']],
    '还复来': [['huan2'], ['fu4'], ['lai2']],
    '倒向': [['dao3'], ['xiang4']],
    '人参观': [['ren2'], ['can1'],['guan1']],
    '睡不着觉': [['shui4'], ['bu4'], ['zhao2'], ['jiao4']],
    '盛满': [['cheng2'], ['man3']],
    '宝宝': [['bao3'],['bao1']],
    '小宝宝': [['xiao3'], ['bao3'],['bao1']],
    "量了": [["liang2"], ["le"]],
    "得好好": [["dei3"], ["hao3"], ["hao3"]],
    "要还" : [["yao4"], ["huan2"]],
    "哪吒": [['ne2'], ['zha1']],
    "传记": [['zhuan4'], ['ji4']],
    "这道奇数":[['zhe4'],['dao4'],['ji1'],['shu4']],
    "调了一会琴弦": [['tiao2'], ['le'], ['yi2'], ['hui4'], ['qin2'], ['xian2']],
    "调了一会儿琴弦": [['tiao2'], ['le'], ['yi2'], ['hui4'], ['er'], ['qin2'], ['xian2']],
    "调吉他": [['tiao2'], ['ji2'], ['ta1']],
    "得重算":[['dei3'],['chong2'],['suan4']],
    "应是":[['ying1'],['shi4']],
    "找到了":[['zhao3'],['dao4'],['le']],
    "数得不亦乐乎": [['shu3'], ['de5'], ['bu4'], ['yi4'], ['le4'], ['hu1']],
    "车行": [['che1'], ['hang2']],
    "重发":[['chong2'], ['fa1']],
    "重写一遍":[['chong2'],['xie3'], ['yi1'],['bian4']],
    "谁知盘中餐":[['shui2'],['zhi1'],['pan2'], ['zhong1'], ['can1']],
    "赶得上":[['gan3'], ['de'], ['shang4']],
    "还款":[['huan2'],['kuan3']],
    "查查":[['cha2'],['cha2']],
    "撒在田里":[['sa3'], ['zai4'],['tian3'], ['li3']],
    "调高一点": [["tiao2"], ["gao1"], ["yi4"], ["dian3"]],
    "没收到": [["mei2"], ["shou1"], ["dao4"]],
    "清清楚楚": [["qing1"], ["qing1"], ["chu3"], ["chu3"]],
    "清清楚楚地": [["qing1"], ["qing1"], ["chu3"], ["chu3"], ["de"]],
    "还清清楚楚地": [["hai2"], ["qing1"], ["qing1"], ["chu3"], ["chu3"], ["de"]],
    "一目了然": [["yi1"], ["mu4"], ["liao3"], ["ran2"]],
    "了如指掌": [["liao3"], ["ru2"], ["zhi3"], ["zhang3"]],
    "伯伯": [["bo2"], ["bo"]],
    "待会儿": [["dai1"], ["hui4"], ["er"]],
    "表述为": [["biao3"], ["shu4"], ["wei2"]],
    "滑倒":[["hua2"], ["dao3"]],
    "吃一堑长一智": [["chi1"], ["yi1"], ["qian4"], ["zhang3"], ["yi1"], ["zhi4"]],
    "先帝创业未半而中道崩殂": [["xian1"], ["di4"], ["chuang4"], ["ye4"], ["wei4"], ["ban4"], ["er2"], ["zhong1"], ["dao4"], ["beng1"], ["cu2"]],
    "小心翼翼地": [["xiao3"], ["xin1"], ["yi4"], ["yi4"], ["de"]],
    "严丝合缝地": [["yan2"], ["si1"], ["he2"], ["feng4"], ["de"]],
    "那得要": [["na4"], ["dei3"], ["yao4"]],
    "框架": [["kuang4"], ["jia4"]],
    "薄礼": [["bo2"], ["li3"]],
    "曾国藩": [["zeng1"], ["guo2"], ["fan1"]],
    # Matcha whole-span pinyin regressions. Keep the shortest context that
    # fixes the reading; unlike VITS these values are complete TONE3 tokens.
    "得重新": [["dei3"], ["chong2"], ["xin1"]],
    "种了": [["zhong4"], ["le5"]],
    "不紧不慢地": [["bu4"], ["jin3"], ["bu4"], ["man4"], ["de5"]],
    "有条不紊地": [["you3"], ["tiao2"], ["bu4"], ["wen3"], ["de5"]],
    "抗得住": [["kang4"], ["de5"], ["zhu4"]],
    "长时间": [["chang2"], ["shi2"], ["jian1"]],
    "数一下": [["shu3"], ["yi1"], ["xia4"]],
    "高兴": [["gao1"], ["xing4"]],
    "切菜": [["qie1"], ["cai4"]],
    "背着孩子": [["bei1"], ["zhe5"], ["hai2"], ["zi5"]],
    "一点一滴地": [["yi1"], ["dian3"], ["yi1"], ["di1"], ["de5"]],
    "积累": [["ji1"], ["lei3"]],
    "中奖": [["zhong4"], ["jiang3"]],
    "中了大奖": [["zhong4"], ["le5"], ["da4"], ["jiang3"]],
    "一次次地": [["yi1"], ["ci4"], ["ci4"], ["de5"]],
    "不好意思地": [["bu4"], ["hao3"], ["yi4"], ["si5"], ["de5"]],
    "刺骨地": [["ci4"], ["gu3"], ["de5"]],
    "很耐心地": [["hen3"], ["nai4"], ["xin1"], ["de5"]],
    "慢慢地": [["man4"], ["man4"], ["de5"]],
    "快乐地": [["kuai4"], ["le4"], ["de5"]],
    "警惕地": [["jing3"], ["ti4"], ["de5"]],
    # The frozen checkpoint has no da5 token; same-syllable inference fallback.
    "疙瘩": [["ge1"], ["da5"]],
    "自忖": [["zi4"], ["cun3"]],
    "呼吸着": [["hu1"], ["xi1"], ["zhe5"]],
    "急得": [["ji2"], ["de5"]],
    "变得": [["bian4"], ["de5"]],
    "梳理得": [["shu1"], ["li3"], ["de5"]],
    "佩服得很": [["pei4"], ["fu2"], ["de5"], ["hen3"]],
    "放得开": [["fang4"], ["de5"], ["kai1"]],
    "羞愧得要死": [["xiu1"], ["kui4"], ["de5"], ["yao4"], ["si3"]],
    "抓空去": [["zhua1"], ["kong4"], ["qu4"]],
    "我倒是": [["wo3"], ["dao4"], ["shi4"]],
    "得了满分": [["de2"], ["le5"], ["man3"], ["fen1"]],
}

# Frozen VITS segmentation hints. Pronunciation still comes from custom_dict;
# these entries only preserve the word boundaries consumed by ToneSandhi.
jieba_phrases = (
    "华为", "藏塔", "一次次地", "不好意思地", "严丝合缝地", "刺骨地",
    "很耐心地", "慢慢地", "快乐地", "警惕地", "那得要",
)
